system "ICEBREAK/ADDICESVR SVRID(SAMPLES) TEXT('IceBreak samples') SVRPORT(60060) HTTPPATH('/www/icebreak-samples') WWWDFTDOC('default.html') "
system "ICEBREAK/STRICESVR SAMPLES"
system "ICEBREAK/WRKICESBS"
